// Copyright 2026, AsteriskNG contributors
// SPDX-License-Identifier: GPL-3.0

package engine.root

import features.resources.runtime.writeAtomically
import utils.shellQuote
import java.io.File

internal fun RootStartConfig.writeRootStopScript(cleanupRulesCommand: String) {
    writeAtomically(File(runtimeLayout.stopScriptPath)) { output ->
        output.write(
            buildRootStopScript(
                runtimeLayout = runtimeLayout,
                uid = RootXrayUid,
                gid = RootXrayGid,
                cleanupRulesCommand = cleanupRulesCommand,
            ).toByteArray(Charsets.UTF_8),
        )
    }
}

internal fun buildRootStopScript(
    runtimeLayout: RootRuntimeLayout,
    uid: Int,
    gid: Int,
    cleanupRulesCommand: String,
): String {
    val ebpfCleanupCommand = runtimeLayout.buildStopRootEbpfCommand()
    return buildString {
        appendScript(
            $$"""
            #!/system/bin/sh
            # Generated by AsteriskNG. This is the sole ROOT proxy stop entrypoint.

            set -u

            ASTERISKD_PID_FILE=$${runtimeLayout.asteriskdPidPath.shellQuote()}
            ASTERISKD_READY_FILE=$${runtimeLayout.asteriskdReadyPath.shellQuote()}
            ASTERISKD_STATE_FILE=$${runtimeLayout.asteriskdStatePath.shellQuote()}
            ASTERISKD_EXECUTABLE=$${runtimeLayout.asteriskdPath.shellQuote()}
            XRAY_PID_FILE=$${runtimeLayout.pidPath.shellQuote()}
            XRAY_EXECUTABLE=$${runtimeLayout.xrayCorePath.shellQuote()}

            # Verify both executable identity and uid/gid before signaling a PID from a file.
            matches_expected_process() {
                process_pid="$1"
                expected_executable="$2"
                expected_uid="$3"
                expected_gid="$4"

                kill -0 "$process_pid" 2>/dev/null || return 1
                cmdline="$(tr '\0' ' ' < /proc/"$process_pid"/cmdline 2>/dev/null || true)"
                executable="$(readlink /proc/"$process_pid"/exe 2>/dev/null || true)"
                matched=0
                case "$cmdline" in *"$expected_executable"*) matched=1 ;; esac
                [ "$executable" = "$expected_executable" ] && matched=1
                [ "$matched" = "1" ] || return 1

                uid_line="$(grep '^Uid:' /proc/"$process_pid"/status 2>/dev/null || true)"
                set -- $uid_line
                [ "${3:-}" = "$expected_uid" ] || [ "${5:-}" = "$expected_uid" ] || return 1
                gid_line="$(grep '^Gid:' /proc/"$process_pid"/status 2>/dev/null || true)"
                set -- $gid_line
                [ "${3:-}" = "$expected_gid" ] || [ "${5:-}" = "$expected_gid" ] || return 1
            }

            # Restore only values captured by asteriskd before a forced termination.
            restore_asteriskd_ipv6_state() {
                [ -r "$ASTERISKD_STATE_FILE" ] || return 0
                while IFS=' ' read -r iface value; do
                    case "$iface" in ''|*/*|all|lo) continue ;; esac
                    case "$value" in
                        0|1)
                            sysctl_path="/proc/sys/net/ipv6/conf/$iface/disable_ipv6"
                            [ -e "$sysctl_path" ] && printf '%s\n' "$value" > "$sysctl_path" 2>/dev/null || true
                            ;;
                    esac
                done < "$ASTERISKD_STATE_FILE"
                rm -f "$ASTERISKD_STATE_FILE" 2>/dev/null || true
            }

            clear_asteriskd_markers() {
                rm -f "$ASTERISKD_PID_FILE" "$ASTERISKD_READY_FILE" 2>/dev/null || true
            }

            # Normal stop waits for asteriskd to restore IPv6. Forced termination restores it here.
            stop_asteriskd() {
                asteriskd_pid="$(cat "$ASTERISKD_PID_FILE" 2>/dev/null || true)"
                if [ -n "$asteriskd_pid" ] &&
                    matches_expected_process "$asteriskd_pid" "$ASTERISKD_EXECUTABLE" $${RootAsteriskdUid} $${RootAsteriskdGid}; then
                    kill "$asteriskd_pid" 2>/dev/null || true
                    asteriskd_attempt=0
                    while [ "$asteriskd_attempt" -lt 20 ] && kill -0 "$asteriskd_pid" 2>/dev/null; do
                        asteriskd_attempt=$((asteriskd_attempt + 1))
                        sleep 0.1
                    done
                    if kill -0 "$asteriskd_pid" 2>/dev/null; then
                        restore_asteriskd_ipv6_state
                        kill -9 "$asteriskd_pid" 2>/dev/null || true
                    fi
                fi
                clear_asteriskd_markers
            }

            stop_xray() {
                xray_pid="$(cat "$XRAY_PID_FILE" 2>/dev/null || true)"
                if [ -n "$xray_pid" ] && matches_expected_process "$xray_pid" "$XRAY_EXECUTABLE" $${uid} $${gid}; then
                    kill "$xray_pid" 2>/dev/null || true
                    sleep 0.2
                    kill -9 "$xray_pid" 2>/dev/null || true
                fi
                rm -f "$XRAY_PID_FILE" 2>/dev/null || true
            }

            # Mode-specific iptables/ip rules and BPF cleanup commands are inserted below.
            cleanup_network_rules() {
            """,
        )
        append(cleanupRulesCommand)
        if (!cleanupRulesCommand.endsWith('\n')) append('\n')
        append(ebpfCleanupCommand)
        if (ebpfCleanupCommand.isNotBlank() && !ebpfCleanupCommand.endsWith('\n')) append('\n')
        appendScript(
            $$"""
            }

            main() {
                case "${1:-}" in
                    --normal)
                        stop_asteriskd
                        ;;
                    --from-asteriskd)
                        # asteriskd already restored IPv6 state and exec'd this script.
                        clear_asteriskd_markers
                        ;;
                    *)
                        echo "Usage: $0 --normal | --from-asteriskd" >&2
                        return 64
                        ;;
                esac

                stop_xray
                cleanup_network_rules
                rm -f "$ASTERISKD_STATE_FILE" 2>/dev/null || true
            }

            main "$@"
            """,
        )
    }
}
